### ISSUE TITLE
[ToDo] Typos and smaller issues 

### ISSUE THREAD

**Issue by LRydin** [LRydin/Power-Grid-Frequency#43]
Small issues:
 - [ ] The location for the Krakow measure is off, it is not pointing to Krakow.
 - [ ] The recordings of the 2013 data in the Nordic Grid have the KIT logo on it when they should not.
 - [ ] Add different sampling rates to the README.

[to be continued]
